services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    entrypoint: php artisan octane:frankenphp --host=localhost --port=443 --admin-port=2019 --https
    ports:
      - 443:443
      - 443:443/udp
    tty: true

volumes:
  caddy_data:
  caddy_config: