services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - caddy_data:/data
      - caddy_config:/config
    entrypoint: /entrypoint.sh
    ports:
      - 443:443
      - 443:443/udp
    tty: true

volumes:
  caddy_data:
  caddy_config: